project:
  type: website
  output-dir: docs

website:
  title: "Nikolay R. Dyakov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



