---
title: "Publications"
---

## Papers

1.  Dyakov, N. 2019. [Testing for assembly rules along disturbance gradients in a riparian broadleaved forest.](https://www.researchgate.net/publication/329876768_Testing_for_assembly_rules_along_disturbance_gradients_in_a_riparian_broadleaved_forest) Applied Ecology and Environmental Research 17 (1): 1-13
2.  Dyakov, N. 2016. [Spatial distribution of some alien plants across a restricted mountainous area.](https://www.researchgate.net/publication/312291466_Spatial_distribution_of_some_alien_plants_across_a_restricted_mountainous_area) Contemporary Problems of Ecology 9: 663-673
3.  Dyakov, N. 2016. [Spatial distribution of dominant plant species according to local environmental gradients.](https://www.researchgate.net/publication/292538743_Spatial_distribution_of_dominant_plants_species_according_to_local_environmental_gradients) Applied Ecology and Environmental Research 14: 327-347
4.  Dyakov, N. 2016. [Modeling plant species diversity pattern in a local environmental space.](https://www.researchgate.net/publication/308777373_Modelling_plant_species_diversity_pattern_in_a_local_environmental_space) Applied Ecology and Environmental Research 14: 441-459
5.  Dyakov, N. 2015. [Rare plant distribution modeling using indirect environmental gradients.](https://www.researchgate.net/publication/282275518_Rare_plant_distribution_modeling_using_indirect_environmental_gradients) Russian Journal of Ecology 46: 332-338
6.  Gruychev, G., Dyakov, N. & Dimitrov, D. 2014. [Habitat variables influencing chukar partridge decrease in Southeastern Bulgaria.](https://www.researchgate.net/publication/269267111_Habitat_variables_influencing_chukar_partridge_decrease_in_Southeastern_Bulgaria) Folia Zoologica 63: 171-179.
7.  Dyakov, N. 2014. [Gradient analysis of vegetation on the south slope of Vitosha mountain, Southwest Bulgaria.](https://www.researchgate.net/publication/276230539_Gradient_analysis_of_vegetation_on_the_south_slope_of_Vitosha_Mountain_Southwest_Bulgaria) Applied Ecology and Environmental Research 12: 1003-1025.
8.  Dyakov, N. & Zhelev, P. 2013. [Alien species invasion and diversity of riparian forest according to environmental gradients and disturbance regime.](https://www.researchgate.net/publication/322798215_Alien_species_invasion_and_diversity_of_riparian_forest_according_to_environmental_gradients_and_disturbance_regime) Applied Ecology and Environmental Research 11: 249-272.
9.  Dyakov, N. 2013. [Successional Pattern, Stand Structure and Regeneration of Forest Vegetation According to Local Environmental Gradients.](https://www.researchgate.net/publication/281430079_Successional_Pattern_Stand_Structure_and_Regeneration_of_Forest_Vegetation_According_to_Local_Environmental_Gradients) Ecologia Balkanica Vol. 5, Issue 1, pp. 69-85.
10. Gruychev, G. & Dyakov, N. 2013. [First confirmed breeding of Woodcock (*Scolopax rusticola* L.) in Vitosha Mt (CW Bulgaria).](https://www.researchgate.net/publication/268211512_First_confirmed_breeding_of_Woodcock_Scolopax_rusticola_in_Vitosha_Mountain_CW_Bulgaria) Acrocephalus 151: 213-214.
11. Dyakov, N. 2013. [Gradient analysis: theory, approaches, and application.](https://www.researchgate.net/publication/281430226_GRADIENT_ANALYSIS_THEORY_APPROACHES_AND_APPLICATION) Forest Science 47: 3-20.
12. Dyakov, N. 2012. [Classification of forest vegetation on the south slope of Vitosha Mountain, Western Bulgaria.](https://www.researchgate.net/publication/281429971_CLASSIFICATION_OF_FOREST_VEGETATION_ON_THE_SOUTH_SLOPE_OF_VITOSHA_MOUNTAIN_WESTERN_BULGARIA) Forestry Ideas 43: 57-77.

## MSc

Dyakov, N. 2005. [Spatial Patterns of Small Mammal Communities at Two Regions of Tundja’s Hilly Plain](https://www.researchgate.net/publication/336994486_SPATIAL_PATTERN_AND_DYNAMICS_OF_SMALL_MAMMAL_COMMUNITIES_IN_TWO_REGIONS_OF_TUNDZHA_RIVER'S_HILLY_PLAIN). Student’s Scientific Conference – Bulgarian Biodiversity Foundation.

## PhD

Dyakov, N. 2013. [Gradient analysis of vegetation on the south slope of Vitosha Mountain](https://www.researchgate.net/publication/348778993_Gradient_analysis_of_vegetation_on_the_south_slope_of_Vitosha_Mountain). PhD Thesis, University of Forestry, Sofia, Bulgaria.
